INSERT INTO `software` (`id`, `acronym`, `name`) VALUES 
('1', 'OMG', 'Operating Map of Gastropathy'),
('2', 'LOL', 'Limited Operating Liability'), 
('3', 'TMI', 'Total Mastering of Incisions'),
('4', 'FOMO', 'Fixed Orthodontics Medical Operations'), 
('5', 'LOTR', 'List of Transactions and Redactions'), 
('6', 'NOOB', 'Northern Ozone & Ocean Biome'), 
('7', '', 'Alternative Sewage System'), 
('8', 'ROFL', 'Relational Observation System Limited'), 
('9', '', 'Fast Family Finder'), 
('10', 'SuX', 'Sustainable Xeriscaping'), 
('11', 'WTF', 'World Terrain & Forestry'),
('12', 'WUT', 'Web Utility Table'), 
('13', 'DUH', 'Data & Utility Heuristics'),
('14', 'OB1', 'Observation (version 1'), 
('15', 'NOOB', 'National Ozone Observatory Bot'), 
('16', 'HUH', 'Heart Ultrasound Heatmaps'), 
('17', 'FML', 'Free MySQL Logger'), 
('18', 'HAHA', 'Heart, Abdomen, and Head Assessor'), 
('19', 'WEWE', 'Waste Electronic & Wireless Equipment'), 
('20', '', 'Biosphere Air and Gas Interpreter'), 
('21', 'ORLY', 'Original Record of Landscape and Yards'), 
('22', 'SAM', 'Selected Analytical Methods'), 
('23', '', 'Storm Water Management'), 
('24', 'PERS', 'Planetary Environmental Reference System'), 
('25', 'SASEE', 'Snowmed Analyzer System Extended Edition'), 
('26', 'PACS', 'Picture Archive and Communication System'), 
('27', 'RIS', 'Radiology Information System'), 
('28', 'DUMB', 'Download Urgent Medical Backups'), 
('29', 'PIP', 'Pharmaceutical Information Program'), 
('30', '', 'Remote Health Checker'), 
('31', '', 'Remote Stroke Checker'), 
('32', '', 'Chronic Disease Management'), 
('33', '', 'Ambulance Schedule System'), 
('34', '', 'Care Manager'), 
('35', 'LIS', 'Lab Information System'), 
('36', 'PAT', 'Patient Admitter Tool'), 
('37', '', 'Spillage Locator Tool'), 
('38', '', 'Environmental Assessor Tool'), 
('39', 'SAS', 'Statistical Analysis System'), 
('40', 'SPSS', 'Statistical Package for Social Sciences'), 
('41', '', 'Cisco WebEx'), 
('42', '', 'Homecare System'), 
('43', 'EMR', 'Electronic Medical Record (Viewer)'), 
('44', '', 'eHealthChart'), 
('45', '', 'Environmental Home Manager'), 
('46', 'CDR', 'Clinical Data Repository'), 
('47', 'NOOBS', 'Netcare Occupation & Observation Base System'), 
('48', 'FAD', 'Find a Doctor'), 
('49', 'DPV', 'Drug Profile Viewer'), 
('50', 'AT-AT', 'Abdomen Tissue and Analysis Tool'), 
('51', 'PCV', 'Provider Coverage Viewer'), 
('52', 'TMI', 'Transcription Magic Interpreter'), 
('53', '', 'PharmaCare'), 
('54', 'PRS', 'Provider Registry System'), 
('55', 'ELSI', 'Electronic Lab System Interpolator'), 
('56', '', 'myeHealth (For British Columbia)'), 
('57', '', 'eReferral'), 
('58', '', 'myeHealth (For Alberta, Saskatchewan, and Manitoba'), 
('59', '', 'Cleaning Product Analyzer'), 
('60', '', 'Greenhouse Gas Analyzer'), 
('61', 'PAD', 'Pollution Alerts Datamart'), 
('62', 'WALDO', 'Water and Land Data Observer'), 
('63', '', 'Waste Observation System'), 
('64', '', 'myeHealth (For Ontario'), 
('65', '', 'myeHealth (For Quebec'), 
('66', '', 'myeHealth (For Yukon, Northwest Territories, Nunavut'), 
('67', 'WASSUP', 'Weather Analyzer Software System Unix Platform'), 
('68', 'WOOKEEE', 'Weather and Ozone Observation Knowledge Emulator Enterprise Edition'), 
('69', '', 'Microstrategy'), 
('70', '', 'myeHealth (For New Brunswick, PEI, Nova Scotia, Newfoundland and Labrador)'), 
('71', '', 'Clinical Admission Manager'), 
('72', '', 'Ambulance Supply System'), 
('73', '', 'TeleCare'), 
('74', 'SIS', 'Surgical Information System');